ktor:
    deployment:
        port: 8080
    application:
        modules:
            - app.saaslaunchpad.ApplicationKt.module
db:
    url: "jdbc:postresql://localhost:5432/saaslaunchpadapp_db"
    user: "postgres"
    pass: ""
    pool: 2
